### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by emmamarkle** [sachin-sankar/swiftshadow#28]
I copied this code from the Shiftshadow website and keep getting this error...

Code copied from website:
```
from swiftshadow import QuickProxy
from requests import get

proxy = QuickProxy()
resp = get('https://checkip.amazonaws.com', proxies={proxy[1]: proxy[0]})
print(resp.text)
```

Error message 
```
Traceback (most recent call last):
  File "filename", line 1, in <module>
    from swiftshadow import QuickProxy
  File " filename", line 1, in <module>
    from swiftshadow.providers import Providers
  File " filename", line 14
    proxy = [f'{proxy['host']}:{proxy['port']}',proxy['protocol']]
                       ^
SyntaxError: f-string: unmatched '['
```

**Comment by sachin-sankar** [comment]
Have started to look into the issue.

**Comment by shayoyem** [comment]
Fixed this issue by updating my python from 3.9.x to 3.12.x

**Comment by whitks** [comment]
fixed this issue by replacing ' ' with "" with :
proxy = [f'{proxy["host"]}:{proxy["port"]}',proxy["protocol"]]

**Comment by cyborgdennett** [comment]
if you want to use in colab do this:
```colab
!pip install swiftshadow
!sed -i "s/proxy = \[f'{proxy\['host']}:{proxy\['port']}',proxy\['protocol']]/proxy = \[f'{proxy\[\"host\"]}:{proxy\[\"port\"]}\',proxy\[\'protocol\']]/g" /usr/local/lib/python3.10/dist-packages/swiftshadow/providers.py
```
